name: E2E test run
on:
  workflow_dispatch:
    inputs:
      workers_count:
        description: 'Please provide number of workers for tests execution'
        type: number
        default: 3
      test_type:
        type: choice
        description: 'Select the type of tests to run'
        options:
          - 'e2e_chrome'
          - 'e2e_safari'
          - 'e2e_firefox'
jobs:
  Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start ${{ inputs.test_type }} test
        run: npx playwright test --project=${{ inputs.test_type }} --workers=${{ inputs.workers_count }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ inputs.test_type }}
          path: playwright-report/
          retention-days: 1
      - name: Create index page
        if: always()
        run: |
          mkdir -p temp-pages/reports/${{ github.run_number }}-${{ inputs.test_type }}
          cp -r playwright-report/* temp-pages/reports/${{ github.run_number }}-${{ inputs.test_type }}/

          # Создаем индексную страницу
          cat > temp-pages/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>Test Reports</title>
              <meta charset="utf-8">
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .report-link { 
                      display: block; 
                      padding: 10px; 
                      margin: 10px 0; 
                      background: #f5f5f5; 
                      text-decoration: none; 
                      border-radius: 5px; 
                  }
                  .report-link:hover { background: #e0e0e0; }
              </style>
          </head>
          <body>
              <h1>Playwright Test Reports</h1>
              <a href="reports/${{ github.run_number }}-${{ inputs.test_type }}/index.html" class="report-link">
                  Latest Report: Run #${{ github.run_number }} - ${{ inputs.test_type }}
              </a>
          </body>
          </html>
          EOF

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp-pages
          keep_files: true
