name: E2E test run
on:
  workflow_dispatch:
    inputs:
      workers_count:
        description: 'Please provide number of workers for tests execution'
        type: number
        default: 3
      test_type:
        type: choice
        description: 'Select the type of tests to run'
        options:
          - 'e2e_chrome'
          - 'e2e_safari'
          - 'e2e_firefox'
jobs:
  Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start ${{ inputs.test_type }} test
        run: npx playwright test --project=${{ inputs.test_type }} --workers=${{ inputs.workers_count }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ inputs.test_type }}
          path: playwright-report/
          retention-days: 1
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          destination_dir: reports/${{ github.run_number }}-${{ inputs.test_type }}
          keep_files: true
